site_name: mbed OS 5 Handbook

docs_dir: docs

pages:
- ['index.md','Introduction to the mbed OS 5 handbook']
- ['getting_started/first_program.md', 'Creating applications on mbed OS', 'Introduction']
- ['getting_started/blinky_cli.md', 'Creating applications on mbed OS', 'First application on mbed CLI']
- ['getting_started/blinky_compiler.md', 'Creating applications on mbed OS', 'First application on mbed Online Compiler']

